#!/usr/bin/env python3
"""Generate minimal compatibility entry points from the canonical SKILL.md."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def render(title: str) -> str:
    digest = hashlib.sha256((ROOT / "SKILL.md").read_bytes()).hexdigest()[:12]
    return f"""<!-- GENERATED by scripts/generate_compat_docs.py; skill-sha256={digest} -->
# {title} — article-revision

`SKILL.md` is the authoritative runtime contract. Read it completely, select
exactly one execution mode, and then load only the workflow and reference files
linked by that route.

Compatibility entry points must not restate the lifecycle. In particular,
diagnosis, direct application, tracked rounds, automatic revision, closure, and
Git authorization are defined only by `SKILL.md`, `workflow/11-direct-apply.md`,
`workflow/13-content-structure.md`, and `workflow/07-git-checkpoint.md`.

If this file appears inconsistent with `SKILL.md`, stop and regenerate it with:

```bash
python scripts/generate_compat_docs.py
```
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = {
        ROOT / "AGENTS.md": render("AGENTS.md"),
        ROOT / "OPENCODE.md": render("OPENCODE.md"),
    }
    stale: list[Path] = []

    for path, content in expected.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"generated={path.name}")

    if stale:
        for path in stale:
            print(f"stale={path.name}")
        return 1
    if args.check:
        print("compat-docs=ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
